### ISSUE TITLE
0.20.0 release planning

### ISSUE THREAD

**Issue by djc** [rustls/rustls#813]
I think we're in a pretty good shape at this point. Work remaining:

- [x] #789 is a pretty impactful public API change
- [x] #799 fixes the session resumption issues from #797
- [x] #787 has a minor public API change, and solves a somewhat popular issue

Unfortunately work on tokio-rustls appears to be [stalled](https://github.com/tokio-rs/tls/pull/68) for now. The tokio-rustls implementation of the `Acceptor` API works for a little while but then starts timing out. That seems unlikely to be an issue in rustls, though (for now there is no local reproduction path).

**Comment by djc** [comment]
I suppose we should also consider #803 before the release. The recommendations made there make sense to me.

**Comment by djc** [comment]
Everything has been merged here. Follow-up question about the changes from #819:

> Should we make CT off by default (no need to call `without_certificate_transparency_logs()`), enabled by calling the builder method explicitly in one of the later stages? (That is, leave it disabled implicitly?)

**Comment by djc** [comment]
Solved that in #826. @ctz do you want to do another beta or shall we kick this thing out already?

**Comment by djc** [comment]
(I can also take care of releasing it if you prefer, let me know if there are any steps I should be sure not to miss.)

**Comment by ctz** [comment]
https://crates.io/crates/rustls/0.20.0

> (I can also take care of releasing it if you prefer, let me know if there are any steps I should be sure not to miss.)

For the future I've written these down on https://github.com/rustls/rustls/blob/main/RELEASING.md

**Comment by djc** [comment]
Thanks!
